### ISSUE TITLE
Documentation request: Please add a line or two about potential use cases

### ISSUE THREAD

**Issue by sesam** [damnever/goodog#9]
I came looking for a reverse proxy. I also know that I don't know enough to figure out where and how conversion between HTTP/1.1 and newer versions should go. I just went through https://http3-explained.haxx.se/ to refresh my memory. Looks almost like the same ideas from original QUIC are still being worked on 5+ years later :)

**Comment by sesam** [comment]
Are you using this to bridge long distance / bad networks? Maybe using Caddy as a reverse proxy? Then this is maybe halfway to what Cloudflare's Railgun does?

**Comment by damnever** [comment]
It's a [transparent proxy](https://en.wikipedia.org/wiki/Proxy_server#Transparent_proxy).

I used to use it to transfer VPN traffic. The reason is that I want to 1) take the advantage of HTTP/3(UDP) and 2) use the 80/443 port (use caddy or other proxies). But unfortunately, it doesn't work as good as TCP, possibly because of the great firewall in our country.
